#!/usr/bin/env sh

# An fzf prompt to unmount drives.
# Please see 'fmount' for more information

fzf_suffix=" > "
unmountusb() {
	[ -z "$drives" ] && exit
	chosen=$(echo "$drives" | fzf -i --prompt="Unmount which drive?$fzf_suffix" | awk '{print $1}')
	[ -z "$chosen" ] && exit
	sudo -A umount "$chosen" && echo "$chosen has been unmounted."
	}

unmountandroid() { \
	chosen=$(awk '/jmtpfs/ {print $2}' /etc/mtab | fzf -i --prompt="Unmount which device?$fzf_suffix")
	[ -z "$chosen" ] && exit
	sudo -A umount -l "$chosen" && echo "Android device $chosen unmounted."
	}

asktype() { \
	case "$(printf "USB\\nAndroid" | fzf -i --prompt="Unmount a USB drive or Android device?$fzf_suffix")" in
		USB) unmountusb ;;
		Android) unmountandroid ;;
	esac
	}

drives=$(lsblk -nrpo "name,type,size,mountpoint" | awk '$2=="part"&&$4!~/\/boot|\/home$|SWAP/&&length($4)>1{printf "%s (%s)\n",$4,$3}')

if ! grep jmtpfs /etc/mtab; then
	[ -z "$drives" ] && echo "No drives to unmount." &&  exit
	unmountusb
else
	if [ -z "$drives" ]
	then
	       	unmountandroid
	else
		asktype
	fi
fi
